Remove line breaks in OSError messages (Windows)
Before:
```
Error: unhandled exception: Не удается найти указанный файл.
 [OSError]
```
After:
```
Error: unhandled exception: Не удается найти указанный файл.  [OSError]
```